<div class="container-fluid h-100">
	<div class="row">
    
    <div class="col-lg-6 pt-5 banner">
    	<img style="width: 100%" src="/img/TESTEEE.png">
    </div>

    <div class="col-lg-6 pt-4 pl-5 pr-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>

			<?php if($this->view->login == 'erro') { ?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Acompanhe o clã de uma nova forma</h1>

				<h2 class="mt-5 mb-5 subtitle">Participe hoje do Twitter do Clã.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>